import ACCore
import Foundation

/// Split (SPEC.md §4.19 capability 4) and merge (capability 5) with real
/// ⌘Z/⌘⇧Z undo/redo — split into its own file for the same reason
/// `+Delete.swift`/`+BoundaryDragging.swift` already are. Closes the real,
/// confirmed gap `+Delete.swift`'s own doc comment flagged: SPEC.md already
/// specified an inverse `UndoManager` registration for both split and merge,
/// but neither actually registered one.
///
/// **Same registration-timing rule as `+Delete.swift`, for the same reason:**
/// the next inverse action is registered synchronously, before the async
/// I/O it belongs to starts — required for `UndoManager` to correctly
/// alternate `registerUndo` calls onto the *redo* stack while this code is
/// itself running as the target of a previous undo/redo, not only after.
///
/// **Split's own undo needs the second (freshly-created) cue's ID at
/// registration time, before the split call that creates it returns** — so,
/// unlike delete/reinsert, the ID is generated by the ViewModel up front and
/// passed into `UpdateCueUseCase.split(secondCueID:)` rather than left to
/// that method's own default.
///
/// **Both split and merge pre-check their own eligibility condition (the
/// exact same guard `UpdateCueUseCase.split`/`.merge` apply internally,
/// via the now-`public` `splitEpsilonSeconds`/`contiguityEpsilonSeconds`)
/// before registering anything.** Without this, an ineligible attempt —
/// silently absorbed as a no-op per SPEC.md §4.15, not a real error — would
/// still leave a bogus undo action registered for a mutation that never
/// happened, which would then fail confusingly if ever invoked.
extension CueDetectionReviewViewModel {
    /// An ⌥-click within a cue's plotted region — SPEC.md §4.15. Clicks
    /// outside any cue's region (silence/gap space) find no containing cue
    /// and are correctly a no-op.
    public func splitRequested(atSeconds seconds: Double, undoManager: UndoManager?) {
        guard let original = cues.first(where: { cue in
            guard let start = cue.startTimecode else { return false }
            let end = start.offsetSeconds + cue.duration.seconds
            return seconds > start.offsetSeconds && seconds < end
        }) else { return }
        guard let start = original.startTimecode else { return }
        let originalEnd = start.offsetSeconds + original.duration.seconds
        // Mirrors UpdateCueUseCase.split's own guard exactly — an ineligible
        // attempt must stay a silent no-op, not register a bogus undo.
        guard seconds > start.offsetSeconds + UpdateCueUseCase.splitEpsilonSeconds,
              seconds < originalEnd - UpdateCueUseCase.splitEpsilonSeconds
        else { return }

        performSplit(
            SplitUndoContext(
                firstCueID: original.id,
                secondCueID: UUID(),
                atOffsetSeconds: seconds,
                originalStartTimecode: start,
                originalDuration: original.duration
            ),
            undoManager: undoManager
        )
    }

    private func performSplit(_ context: SplitUndoContext, undoManager: UndoManager?) {
        registerUndoForMergeBack(context, undoManager: undoManager)
        Task { [weak self] in
            guard let self else { return }
            do {
                _ = try await updateCueUseCase.split(
                    projectID: projectID,
                    cueID: context.firstCueID,
                    atOffsetSeconds: context.atOffsetSeconds,
                    secondCueID: context.secondCueID
                )
            } catch {
                errorMessage = "Couldn't split the cue."
            }
        }
    }

    private func registerUndoForMergeBack(_ context: SplitUndoContext, undoManager: UndoManager?) {
        guard let undoManager else { return }
        undoManager.registerUndo(withTarget: self) { viewModel in
            viewModel.performMergeBack(context, undoManager: undoManager)
        }
        undoManager.setActionName("Split Cue")
    }

    /// Split's inverse — SPEC.md §4.19: "undo deletes the newly-created
    /// second `Cue` and restores the first `Cue`'s pre-split
    /// `startTimecode`/`duration` — every other field on the first `Cue`
    /// was never touched by split in the first place," so a full-field
    /// restore isn't needed here the way merge's undo needs one below.
    private func performMergeBack(_ context: SplitUndoContext, undoManager: UndoManager?) {
        registerUndoForSplit(context, undoManager: undoManager)
        Task { [weak self] in
            guard let self else { return }
            do {
                try await updateCueUseCase.edit(projectID: projectID, cueID: context.firstCueID) { cue in
                    Cue(
                        id: cue.id,
                        title: cue.title,
                        workNumber: cue.workNumber,
                        duration: context.originalDuration,
                        rightHolders: cue.rightHolders,
                        isArrangementOfProtectedOriginal: cue.isArrangementOfProtectedOriginal,
                        source: cue.source,
                        startTimecode: context.originalStartTimecode,
                        notes: cue.notes
                    )
                }
                try await updateCueUseCase.delete(projectID: projectID, cueID: context.secondCueID)
            } catch {
                errorMessage = "Couldn't undo the split."
            }
        }
    }

    private func registerUndoForSplit(_ context: SplitUndoContext, undoManager: UndoManager?) {
        guard let undoManager else { return }
        undoManager.registerUndo(withTarget: self) { viewModel in
            viewModel.performSplit(context, undoManager: undoManager)
        }
        undoManager.setActionName("Split Cue")
    }

    // MARK: - Merge

    /// Dragging a marker off the waveform strip — eligibility (genuine
    /// contiguity with the preceding cue) is pre-checked here, mirroring
    /// `UpdateCueUseCase.merge`'s own internal guard exactly, so an
    /// ineligible attempt stays the silent no-op SPEC.md §4.15 specifies
    /// ("no merge affordance appears, the drag cancels on release") instead
    /// of registering an undo action for a merge that never happened.
    public func mergeRequested(markerID: Int, undoManager: UndoManager?) {
        guard cues.indices.contains(markerID), markerID > 0 else { return }
        let precedingSnapshot = cues[markerID - 1]
        let followingSnapshot = cues[markerID]
        guard let precedingStart = precedingSnapshot.startTimecode,
              let followingStart = followingSnapshot.startTimecode
        else { return }
        let precedingEnd = precedingStart.offsetSeconds + precedingSnapshot.duration.seconds
        guard abs(precedingEnd - followingStart.offsetSeconds) <= UpdateCueUseCase.contiguityEpsilonSeconds
        else { return }

        performMerge(
            precedingSnapshot: precedingSnapshot,
            followingSnapshot: followingSnapshot,
            atIndex: markerID - 1,
            undoManager: undoManager
        )
    }

    private func performMerge(
        precedingSnapshot: Cue,
        followingSnapshot: Cue,
        atIndex: Int,
        undoManager: UndoManager?
    ) {
        registerUndoForUnmerge(
            precedingSnapshot: precedingSnapshot,
            followingSnapshot: followingSnapshot,
            atIndex: atIndex,
            undoManager: undoManager
        )
        Task { [weak self] in
            guard let self else { return }
            do {
                _ = try await updateCueUseCase.merge(
                    projectID: projectID,
                    precedingCueID: precedingSnapshot.id,
                    cueID: followingSnapshot.id
                )
            } catch {
                errorMessage = "Couldn't merge the cues."
            }
        }
    }

    private func registerUndoForUnmerge(
        precedingSnapshot: Cue,
        followingSnapshot: Cue,
        atIndex: Int,
        undoManager: UndoManager?
    ) {
        guard let undoManager else { return }
        undoManager.registerUndo(withTarget: self) { viewModel in
            viewModel.performUnmerge(
                precedingSnapshot: precedingSnapshot,
                followingSnapshot: followingSnapshot,
                atIndex: atIndex,
                undoManager: undoManager
            )
        }
        undoManager.setActionName("Merge Cues")
    }

    /// Merge's inverse — SPEC.md §4.19's "Undo losslessness" requirement:
    /// "a snapshot-based restore of both original `Cue` records exactly as
    /// they existed immediately before the merge, not a computed reversal
    /// that re-derives the discarded side's values from the merge rules."
    /// `precedingSnapshot`/`followingSnapshot` are exactly that — captured
    /// in `mergeRequested` before `merge` ever ran, so title/notes/
    /// rightHolders lost or combined by the forward merge come back intact.
    /// One field is a known, deliberate exception: `source`, which `edit`'s
    /// own reclassification rule (SPEC.md §4.3) always forces to `.manual`
    /// regardless of the transform's result — matching merge's own forward
    /// direction, which already force-sets `source == .manual` unconditionally,
    /// so this restore is no less exact than the state merge itself produced.
    private func performUnmerge(
        precedingSnapshot: Cue,
        followingSnapshot: Cue,
        atIndex: Int,
        undoManager: UndoManager?
    ) {
        registerUndoForMerge(
            precedingSnapshot: precedingSnapshot,
            followingSnapshot: followingSnapshot,
            atIndex: atIndex,
            undoManager: undoManager
        )
        Task { [weak self] in
            guard let self else { return }
            do {
                try await updateCueUseCase.edit(projectID: projectID, cueID: precedingSnapshot.id) { _ in
                    precedingSnapshot
                }
                try await updateCueUseCase.insertForUndo(
                    projectID: projectID,
                    cue: followingSnapshot,
                    atIndex: atIndex + 1
                )
            } catch {
                errorMessage = "Couldn't undo the merge."
            }
        }
    }

    private func registerUndoForMerge(
        precedingSnapshot: Cue,
        followingSnapshot: Cue,
        atIndex: Int,
        undoManager: UndoManager?
    ) {
        guard let undoManager else { return }
        undoManager.registerUndo(withTarget: self) { viewModel in
            viewModel.performMerge(
                precedingSnapshot: precedingSnapshot,
                followingSnapshot: followingSnapshot,
                atIndex: atIndex,
                undoManager: undoManager
            )
        }
        undoManager.setActionName("Merge Cues")
    }
}

/// Bundles split/merge-back's five snapshot values into one parameter —
/// purely to keep `performSplit`/`registerUndoForMergeBack`/`performMergeBack`/
/// `registerUndoForSplit` under this project's function-parameter-count lint
/// limit; no behavior of its own beyond the pre-split state it carries.
private struct SplitUndoContext {
    let firstCueID: Cue.ID
    let secondCueID: Cue.ID
    let atOffsetSeconds: Double
    let originalStartTimecode: Timecode
    let originalDuration: MediaDuration
}
